### PR TITLE
Fix for #105

### LINKED ISSUE #105: Limit number of results returned by lookup and auto load additional results when user scrolls to bottom of list
@crucialfelix 

In our app we have > 100k names of persons that we would like to be able to search for using ajax_selects.

The current implementation would, in worst case scenarios, result in a major performance drop as the lookup would return far too many items.

I am currently working on a PR that will

 - load only a given number of items from the server with each request (limit)
 - load additional items from the server as soon as the user scrolls down to the bottom of the list (offset)

I still need to flesh things out but I wonder whether such a PR would be appreciated and how soon it could be integrated into the master once all issues have been resolved.

Thanks!

### PR DESCRIPTION
**Pull request by silkentrance**
- fixes #105: roundtrip performance optimizations

### CODE REVIEW

**Comment by silkentrance** [comment]
@crucialfelix Please note that this needs some more work. Feel free to revise this as needed. Thanks!

**Comment by silkentrance** [comment]
The css needed to be altered in order to make the scroll down list work, as per the referenced jsfiddle on which is is actually based.

As for install.sh, this will work in only those environment where bash is the main shell associated with /bin/sh, which is not the case for a standard debian installation. Besides of that, install.sh failed on manage.py syncdb as the symlink towards ../ajax-select was not created before, therefore the change.

As for the lookup channel, the optional offset and limit parameters need to be reimplemented by everyone using this app, something we all would not like to be doing for every lookup and every app we implement.

And as for the optional offset and limit parameters, the user would have to reimplement exactly what is implemented in the PR, something not all users are capable of doing or wanting to do.

As for the inline notes, these are temporarily as this is a work in progress.

As for the examples, these needed to be adjusted so that they will work with the change in behaviour.

As for the complexity, hey, this is github, PR is your friend, community wise.

**Comment by silkentrance** [comment]
Just curious, since this is fork of sjrd/django-ajax-selects, why would you even bother maintaining, since we can always also PR to the main repository.

Or did the original inventor abandon this app?

**Comment by silkentrance** [comment]
Sorry for taking so long, but I have been busy.

Since you say that the PR is overly complex, I would consider the following

 - make a JQuery UI AutoSelect extension for JQuery UI AutoSelect and publish that via the appropriate channels
 - pass in additional request parameters to the lookup by just the request object
 - allow the user to use alternate JQuery UI Widgets instead of the standard AutoSelect

The rest of the issues that have been dealt with in this PR will then be moved to smaller PRs, for example serialization of the JSON which must not be serialized into memory as a whole but rather in smaller bits.

Currently, I have no time for actually doing this, but I will come back to it ASAP.

**Comment by crucialfelix** [comment]
Sorry for the late reply. I'm also really busy right now.


   - allow the user to use alternate JQuery UI Widgets instead of the
   standard AutoSelect

you can already do this. just set *AJAX_SELECT_BOOTSTRAP = False*

this means that it will not load *jquery* or *jquery-ui* and you can do so
yourself
and then just include any version you like.

also you can override the static files by adding them to your own app and
putting that app in front of ajax-selects in your app settings.
django staticfiles searches the installed apps for the first matching path

so you can supply a completely different version of
*ajax_select/js/ajax_select.js* if you need to

and as I said previously, your lookup gets the request so it can do
anything it wants to do.

but in general I think that paginating the results in a select input is an
anti-pattern.
its just usable with that kind of interface. if you have many pages of
results then it should be a larger flat interface.

**Comment by silkentrance** [comment]
@crucialfelix Thanks for the reply. I am currently wrapping my head around jquery ui and unit testing using qunit and phantom.

I think that this PR can be closed for now.

**Pull request closed without merging**
