### PR TITLE
dj21 render() has a new param: renderer

### PR DESCRIPTION
**Pull request by zvolsky**
Without this under dj21rc1:

Traceback (most recent call last):
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 993, in render
    return render_value_in_context(output, context)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/template/base.py", line 972, in render_value_in_context
    value = str(value)
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/utils/html.py", line 397, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/home/vagrant/venv37/lib/python3.7/site-packages/django/forms/boundfield.py", line 93, in as_widget
    renderer=self.form.renderer,
TypeError: render() got an unexpected keyword argument 'renderer'

### CODE REVIEW

**Comment by crucialfelix** [comment]
Thanks.

**Comment by kornikopic** [comment]
Hi, do you have idea when this fix will be released ? Thank you :)

**Comment by crucialfelix** [comment]
As I'm on vacation right now, not until August 20th at the earliest. Sorry.

I haven't tested it yet and need to figure out why unit tests didn't fail
if this was really a breaking change.

You can install python packages from a git URL.

**Comment by kornikopic** [comment]
No problem, thank you for the quick follow up. Enjoy your holidays!

**Comment by kornikopic** [comment]
Maybe I am not good with pip but it seems that @zvolsky's branch is not working.

Here is the command I executed:

`pip install -e git+git://github.com/zvolsky/django-ajax-selects.git@zvolsky_fix_renderer#egg=django-ajax-selects`

`Pip freeze` gives me this output:

`-e git://github.com/zvolsky/django-ajax-selects.git@a677609287f974a4ea672c069d613e1270500d62#egg=django_ajax_selects
`

**Comment by crucialfelix** [comment]
Do you mean that you cannot check it out, or that it isn't working
correctly.

I think it would actually require the dist to be made.

I'll see if I can test and release on the 19th or 20th

**Comment by kornikopic** [comment]
It gives me the same error as previously mentioned. That's why I published the command I executed because I don't understand why it still not working. Maybe @zvolsky forgot some places? I'm at work right now but as soon as I'm back home, I'll post the exact error message I got.

**Comment by crucialfelix** [comment]
Tomorrow morning I'll get this solved and released.  Big client work today.  Thanks for your patience.

**Comment by kornikopic** [comment]
Thanks a lot for your support.

**Comment by crucialfelix** [comment]
Thanks very much for the PR !  

The tests now run against all versions and they do check all the render() of fields.  Doing the release shortly.

**Comment by crucialfelix** [comment]
Released https://pypi.org/project/django-ajax-selects/

**Comment by jonathanmorgan** [comment]
Working great for me with django 2.1.  Thank you!

**Comment by kornikopic** [comment]
@crucialfelix Thank you for the release but it still does not work for me. Here is the stacktrace: 

`Traceback (most recent call last):
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 993, in render
    return render_value_in_context(output, context)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/template/base.py", line 972, in render_value_in_context
    value = str(value)
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/utils/html.py", line 397, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/home/frujo/projects/venvs/oscar/lib/python3.6/site-packages/django/forms/boundfield.py", line 93, in as_widget
    renderer=self.form.renderer,
TypeError: render() got an unexpected keyword argument 'renderer'`

**Comment by kornikopic** [comment]
@crucialfelix  Nevermind. I found the problem. I was using another plugin in my form on another field. Everything's working perfectly! Thank you again for your support and the release.

**Comment by crucialfelix** [comment]
Damn... Oh ok... Great !  Glad to hear it !

**Pull request merged**
