### PR TITLE
fix for django-ajax-selects to work in django 2.2

### PR DESCRIPTION
**Pull request by jsm296**

### CODE REVIEW

**Comment by jsm296** [comment]
Hmmm.  Let me create a branch and a pull request for the way Amrish Parmar suggested and we'll see if it passes.

**Comment by crucialfelix** [comment]
Create a branch from (freshly pulled) develop.  

git checkout -b feature/fix-django22-media-assets

Push that to your fork and then make a PR from there.

Thanks so much for the help!

**Comment by crucialfelix** [comment]
Ah wait, this fix was already merged! We really are just waiting on a release.

I figured out why travis fails too.

**Comment by crucialfelix** [comment]
Ah I see I did try to fix this about a year ago but didn't finish testing it and making the PR.

I just now figured out why travis fails. Will push a fix for that.

**Comment by jsm296** [comment]
OK.  Let me know how else I can help.  Happy to test with the release version if that helps, I have VMS with copies of my applications I can spin up and test with quickly.

**Comment by nimasmi** [comment]
Since this is a Django 2.2 fix, perhaps we could include a change to tox.ini to test against Django 2.2 in CI tests. See https://github.com/crucialfelix/django-ajax-selects/blob/develop/tox.ini#L24

**Comment by crucialfelix** [comment]
This PR is coming from a wrong branch or old fork. There should not be commits for all releases since 2014 included in this PR.

It also needs to branch after the current develop where I fixed the travis configuration.

It *looks* like it will work. But the unit tests are not integration tests, so we need to human-test this on 2.2 and an earlier version.

@nimasmi  and maybe Django 3, but "Following the release of Django 3.0, we suggest that third-party app authors drop support for all versions of Django prior to 2.2."

**Comment by nimasmi** [comment]
I have monkey-patched my field's widgets in a project of mine to set this version of the `_media()` function as their `.media` property, and can confirm it worked in my case.

(I then removed the monkey patch when I realised that simply adding the missing file to the form's Media inner class was a lot less fragile, but that's another story.)

**Comment by Cabalist** [comment]
I'm very interested in getting this merged.  Is a new PR necessary that is based on the right branch?

**Comment by crucialfelix** [comment]
Yes please.

Ryan Jarvis <notifications@github.com> schrieb am Fr., 20. Dez. 2019, 21:59:

**Comment by crucialfelix** [comment]
Fix is merged in #253

**Comment by crucialfelix** [comment]
1.8.0 is out with the fix!  Thanks everyone.

https://pypi.org/project/django-ajax-selects/

**Pull request closed without merging**
