### PR TITLE
Ignore required Attribute for Inputs

### LINKED ISSUE #193: "required" attribute not being cleared when form field has a valid instance
I'm in the process of upgrading a project from Django 1.5 to 1.10 and have upgraded from `django-ajax-selects` 1.3.3 to the latest (1.5.2) but am running into a problem: when I have a form field (single auto-complete) that has a valid instance either pre-added or added after page load, the `required` attribute on the visible field is not being updated correctly. In our existing codebase, the visible form field (i.e., not the hidden id field the Ajax select is actually populating) does not have a `required` attribute in these cases but in every version of this library from 1.4.3 to 1.5.2 the field is incorrectly marked as required. I don't see anywhere in the `helpers.py` or the `ajax-selects.js` where the required field is ever adjusted so I am wondering if something changed between 1.3.3 and more recent versions in the field/ form configuration that I am missing.

FWIW, I have tried upgrading jQuery and jQuery UI to the CDN versions shown in the example project to make sure it's not an issue there. We are also using Bootstrap and bootstrap.js

### PR DESCRIPTION
**Pull request by tclancy**
Closes #193 - happy to add tests but I couldn't get the tests running on the Windows machine I'm on right now.

### CODE REVIEW

**Comment by crucialfelix** [comment]
Thanks. Ignore the failure. I'm not sure how that got through before. Nothing to do with this PR

**Comment by logston** [comment]
Anything I can do to help this get merged? We really need it to upgrade our project.

**Comment by crucialfelix** [comment]
Sorry. I did have a test of this. I didn't see any required attribute at all. Popping it results in an error. What is supplying​ required ? Can you post some example ?

**Comment by tclancy** [comment]
I'm not sure what would be helpful as an example-- this is code I inherited so I'm not that familiar with the package. It's calling `make_ajax_field` on a Django model's field and using this lookup:

```
class OurModelLookup(LookupChannel):
    model = OurModel

    def get_query(self,q,request):
        return OurModel.objects.filter(Q(last_name__icontains=q) | Q(first_name__icontains=q)).order_by('last_name')

    def get_result(self,obj):
        u""" result is the simple text that is the completion of what the person typed """
        return obj.last_name

    def format_match(self,obj):
        """ (HTML) formatted item for display in the dropdown """
        return u"%s" % (escape(obj.first_name + " " + obj.last_name + " " + escape(obj.birth_date)))

    def format_item_display(self,obj):
        """ (HTML) formatted item for displaying item in the selected deck area """
        return u"%s (DOB: %s)" % (escape(obj.first_name + " " + obj.last_name),escape(obj.birth_date))
    
    def check_auth(self,request):
        """ to ensure that nobody can get your data via json simply by knowing the URL.
            also we could choose to return HttpResponseForbidden("who are you?")
            instead of raising PermissionDenied (401 response)
            Our default is to make sure the user is authenticated and active, else raise error.
         """
        if not (request.user.is_authenticated() and request.user.is_active):
            raise PermissionDenied
```

**Comment by crucialfelix** [comment]
I've done a fix now, will be releasing today

**Pull request closed without merging**
