### PR TITLE
Fix for django form's changed_data issue

### PR DESCRIPTION
**Pull request by jose-flores**
This fixes incorrect inclusion of autocompletefields when submitting a form and its value hasn't changed

### CODE REVIEW

**Comment by crucialfelix** [comment]
There is no to_python method on the lookup, so this is basically a hack that you have put in for your specific situation.  Its not a general usage solution.

If there is a specific issue you are trying to fix then you should post an issue describing it.

Sorry, can't accept this one.

**Comment by jose-flores** [comment]
Hello @crucialfelix 

I haven't noticed your reply. 
The issue is the following: When your code relies on the changed_data array of django form, ajax select fields are always included no matter they haven't changed. Ajax lookups try always to coerce to a number. I propose that the lookup can have an option for coercing to the type it's consider best.

**Comment by crucialfelix** [comment]
When you say "your code relies on the changed_data array of django form" do you mean me (something in django-ajax-selects) ? or your own code ?

I don't understand what the issue is with changed_data. Can you demonstrate that or describe it ? If it is a bug then you could file an issue for it.

But I don't think its the job of the Lookup to do this, and we can't push a mysterious and undocumented api on to the developer.

**Comment by jose-flores** [comment]
Let me try to explain it.
As your fields inherits from CharField, the Form's has_changed method always fails because the CharField's to_python always return a string.

Let's say we have this:
class Form(forms.Form):
    myfield = AutcompleteSelect('mychanel')
...

if we make:
if form.is_valid() and myfield in form.changed_data:
    print "Something"

Something will be printed even though no changed to myfield attribute has been requested.

Your field always try to coerce to number via the value_from_datadict but CharField's to_python method returns back a string as I told you before.

The to_python method is the one that at the end is used by Django Form's API, and as model's pk could be also a string we should provide a method to seamlessly support such conversion. There is where it enters the to_python method in the lookup.

I understand your concern about it. Then we should provide the default in the Lookup.

**Comment by jose-flores** [comment]
Hello @crucialfelix 
Any thought on this?

Regards

**Comment by victorddiniz** [comment]
Hey @jose-flores ,
@crucialfelix kinda solved this problem with changed_data of forms at Issue #123, it does work when there is no extra (in case of adminInline).  But mine was this case, so I had to go with your solution which worked fine. Thank you : )

**Pull request closed without merging**
