### PR TITLE
Drop support for Python 2 and Django <2.2

### PR DESCRIPTION
**Pull request by Cabalist**
Noticed I was getting a lot of warnings from this package on my project and took some time to modernize the code and drop support for EoL codebases.

### CODE REVIEW

**Comment by crucialfelix** [comment]
Very much appreciated!  I'm not managing any python codebases at the moment, so I'm not using this myself.

This would of course make a new major version. 

I will give it a look and test it soon.

**Comment by Cabalist** [comment]
I had hoped that tox would kick in on a PR to test across everything but that didn't happen.   There may be issues here until I get that up and running.  :)

**Comment by crucialfelix** [comment]
It is still set to run on travis.  There may be a GitHub action that runs
tox.

You deserve that hacktober free t shirt.

**Comment by Cabalist** [comment]
Ha.   I wish I could say I was in it for the t-shirt but I have the much more neurotic goal of removing all warnings from our app.  ;) 

This should be ready!  `tox` passes for all the environments.

I've left the version bump to you.   2.0.0?

**Review by crucialfelix — APPROVED** [review]

**Comment by crucialfelix** [comment]
Released: https://pypi.org/project/django-ajax-selects/

Thanks again

**Pull request merged**
