### PR TITLE
Support ForeignObjectRel on helpers

### PR DESCRIPTION
**Pull request by alculquicondor**
The field can successfully be created for Foreign Object Relationships, so I decided to include them in the helpers.

However, since it is not a field, extra code needs to be added in the Form (or the calling View or Admin) to populate initial values and persist the changes. I wasn't sure about adding that part of the code.

I'm more than open to feedback.

### CODE REVIEW

**Comment by crucialfelix** [comment]
You have to define an InlineModelAdmin. It cannot appear to be a normal field on the model (because it isn't actually a field on the model at all — it's a field on another model)

https://stackoverflow.com/questions/16070809/how-to-i-show-a-list-of-foreignkey-reverse-lookups-in-the-django-admin-interface

On that inline model admin you can include a form that uses django-ajax-selects. That does work. It means that the section is at the bottom of the form. You can add multiple.

The django admin is for editing a single object, so the form is going to always correspond to the fields on that object.  If you want to build a different UI (that corresponds to the way a human wants to fill out a form) then you have to do that outside of the admin.  You can use django-ajax-selects fields in forms that are not in the admin.

Also see: https://github.com/rpkilby/django-reverse-admin (which is a sketch)

**Comment by alculquicondor** [comment]
I tried to do this as you said (using inline model admin). However, FormSets only appear to support the creation of new objects or the edition of objects already linked. I didn't find a way to use even a regular ChoiceField to select existing objects not yet linked. I will see if the snippet helps.
FTR, The UI I'm trying to build is targetting administrators.

**Comment by crucialfelix** [comment]
Try the included example app.  When you edit a Group (musical group) you can add and edit Releases. 

https://github.com/crucialfelix/django-ajax-selects/blob/develop/example/example/admin.py#L31

I think you are right though — you can't simply select a bunch of Releases and have each of them set or unset their `release.group = group` on save. You could try creating an inline for the join table object, but this is also a hack.

Honestly if I was solving the problem for myself I would write a React ui and use GraphQL to set/unset the items. Myself I avoid the django admin. It's not suitable for all tasks.

**Comment by alculquicondor** [comment]
Then I guess this change is a bit of an stress for the purposes of the library. Feel free to close the PR or point me to the right direction to getting it merged. I already solved the problem I was trying to solve on my project. But as I said, I had to overwrite the save_model in the admin.

**Comment by crucialfelix** [comment]
Oh, you did get it to work ? Can you post a gist of the changes you made to the form (or however you did it) ?   

Right now I just see a PR that doesn't seem to work or add functionality.  I need to see working examples, models, full code.

**Comment by alculquicondor** [comment]
This is the working code https://gist.github.com/alculquicondor/5c30202f81a984791a6bf838e3a62105

Maybe a change could be added to `AjaxSelectAdmin`, or the save for the foreign models could be moved to the form's save. But then this library doesn't have a custom form.

**Comment by crucialfelix** [comment]
It does look like it would work. It's interesting but I guess it's kind of a hack and django-ajax-selects is already doing some odd things. (using a text widget to edit a foreign key)

I'm not yet sure about if or how to include support for that.

Thanks for posting that !

**Comment by alculquicondor** [comment]
Let me know your decision.

**Comment by crucialfelix** [comment]
Closing as it makes things more complicated in the long run. Thanks for posting it though !

**Pull request closed without merging**
