### PR TITLE
Fixes AJAX Selector and dynamic inlines #67

### PR DESCRIPTION
**Pull request by jact**
These changes work in my project.

### CODE REVIEW

**Comment by crucialfelix** [comment]
You are referencing an issue that is closed. 

What is the problem that you are seeing ?

You seem to be suggesting that these elements are not existing on the DOM and are still being created: ` $('.inline-group ul.tools a.add, .inline-group div.add-row a, .inline-group .tabular tr.add-row td a')`

But AFAIK that is not the case. The html is rendered by Django and those elements are on the page.  No ?

**Comment by jact** [comment]
Default inline rows are ok, but the problem occurs when another row is added in the inline form. Then, new field associated with ajax_selects doesn't have the 'ui-autocomplete-input' class.

**Comment by crucialfelix** [comment]
The PR you have here is adding a `setTimeout` inside the `$(document).ready` event handler.

That is not "when another row is added" - its not happening in response to a user event or another javascript event.  This part of the code only happens when the DOM is ready on the initial page load.

**Comment by jact** [comment]
When I started using the version 1.3.3, I had to make a fork with the solution which I send to you. When I upgraded to version 1.4.1, the issue has been reproduced. In fact, I have to add this patch above version 1.4.1.

It's true that not seem to make sense for what you mention... but that's what has worked for me so far.

**Pull request closed without merging**
