### PR TITLE
fix for Django 1.11

### PR DESCRIPTION
**Pull request by dancastellani**
Related issue and description:
https://github.com/crucialfelix/django-ajax-selects/issues/167

### CODE REVIEW

**Comment by dancastellani** [comment]
I also ran the test and they passed on 2.7

**Comment by crucialfelix** [comment]
Thank you !  

It looks correct to me but I'm not positive about 2.0. It would be better if I had a test in there for this.

**Comment by dancastellani** [comment]
How do you want to make this test?
Maybe I can help with it. Let's discuss.

**Comment by crucialfelix** [comment]
That would be great.

Look at the models in tests https://github.com/crucialfelix/django-ajax-selects/blob/develop/tests/models.py

And the lookup tests. You need to set up a relationship of saved models and then write a test that covers that lookup method. When it is running with make test it should test all pythons and djangos. In any case Travis will test the whole matrix.

**Comment by dancastellani** [comment]
hey, I'm supper busy these days and I don't think I'll be able to code something new on this soon. I'm sorry.

**Comment by crucialfelix** [comment]
No prob, I totally understand.  I was just remembering this issue the other day. I'll see if I can get the test in there myself soon.

**Pull request closed without merging**
