### PR TITLE
Add AjaxSelectAdminStackedInline to work similarly to AjaxSelectAdminTabularInline

### PR DESCRIPTION
**Pull request by unklphil**
Uses the same function as existing `get_formset` from AjaxSelectAdminTabularInline.

This adds the plus signs next to the ajax field if the user is allowed to add another instance of the object.

### CODE REVIEW

**Comment by unklphil** [comment]
Undid my Django 1.8 fixes in favour of those in 1.3.6

**Comment by crucialfelix** [comment]
thank you.

I assume this works, but I need to confirm with the example app or preferably with unit testing.

 I'm setting up testing now.

**Comment by unklphil** [comment]
I've added an example of the `AjaxSelectAdminStackedInline` to the example app under groups for releases

**Comment by crucialfelix** [comment]
thanks !

**Pull request merged**
